---
ignored_issues:
  - "Binary Not Signed"

ignored_severity:
  - Info

ignored_file:
  - concrt140.dll
  - msvcp140_1.dll
  - msvcp140_2.dll
  - msvcp140_atomic_wait.dll
  - msvcp140.dll
  - msvcp140_codecvt_ids.dll
  - msvcp140_codecvt_ids.dll
  - vcruntime140.dll
  - vcruntime140_1.dll
