---
name: Release Summary

permissions: read-all

on:
  workflow_call:
    inputs:
      output_prefix:
        description: 'Prefix to add to output artifacts'
        required: false
        default: ''
        type: string

env:
  BDBA: ${{ inputs.output_prefix }}bdba-scan
  HADOLINT: ${{ inputs.output_prefix }}hadolint
  IPLEAKS: ${{ inputs.output_prefix }}ip-leak-scan
  TRIVY: ${{ inputs.output_prefix }}trivy
  COVERITY_L: linux-${{ inputs.output_prefix }}coverity-scan
  COVERITY_W: windows-${{ inputs.output_prefix }}coverity-scan
  DIFF_L: linux-${{ inputs.output_prefix }}diff-report
  DIFF_W: windows-${{ inputs.output_prefix }}diff-report
  AV_S: source-malware-scan
  AV_L: linux-release-build-malware-scan
  AV_W: windows-release-build-malware-scan
  UTEST_L: linux-release-build-utests
  UTEST_W: windows-release-build-utests
  SSCB_L: linux-${{ inputs.output_prefix }}sscb
  SSCB_W: windows-${{ inputs.output_prefix }}sscb
  RHEL86: rhel8.6-release-gen12.5-acceptance
  SLES154: sles15.4-release-gen12.5-acceptance
  U2204: ubuntu22.04-release-gen12.5-acceptance
  U2204_GEN95: ubuntu22.04-release-gen9.5-acceptance
  WIN11: windows11-release-gen12.5-acceptance
  WIN11_GEN95: windows11-release-gen9.5-acceptance


jobs:
  report:
    runs-on: [self-hosted, Linux, docker]
    steps:

      - name: Cleanup workspace
        run: sudo rm -rf ..?* .[!.]* *

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: BOM artifacts
        if: >
          !cancelled()
        run: |
          mkdir -p summary/bom/Linux
          mkdir -p summary/bom/Windows

          cp -r artifacts/$DIFF_L/. summary/bom/Linux/
          cp -r artifacts/$DIFF_W/. summary/bom/Windows/

      - name: SDL artifacts
        if: >
          !cancelled()
        run: |
          mkdir -p summary/sdl/CT7-KnownVulnerabilities
          mkdir -p summary/sdl/CT37-MalwareScan
          mkdir -p summary/sdl/CT39-StaticAnalysis
          mkdir -p summary/sdl/CT151-CompilerFlags
          mkdir -p summary/sdl/CT222-DockerScan
          mkdir -p summary/sdl/CT247-Trivy

          cp artifacts/$BDBA/vulns.csv \
             summary/sdl/CT7-KnownVulnerabilities/vulns.csv
          cp artifacts/$AV_S/report.txt \
             summary/sdl/CT37-MalwareScan/source-report.txt
          cp artifacts/$AV_L/report.txt \
             summary/sdl/CT37-MalwareScan/linux-report.txt
          cp artifacts/$AV_W/report.txt \
             summary/sdl/CT37-MalwareScan/windows-report.txt
          cp artifacts/$COVERITY_L/json/errors_v9_full.json \
             summary/sdl/CT39-StaticAnalysis/linux-coverity.json
          cp artifacts/$COVERITY_L/cvss_report.pdf \
             summary/sdl/CT39-StaticAnalysis/linux-cvss_report.pdf
          cp artifacts/$COVERITY_L/security_report.pdf \
             summary/sdl/CT39-StaticAnalysis/linux-security_report.pdf
          cp artifacts/$COVERITY_W/json/errors_v9_full.json \
             summary/sdl/CT39-StaticAnalysis/windows-coverity.json
          cp artifacts/$COVERITY_W/cvss_report.pdf \
             summary/sdl/CT39-StaticAnalysis/windows-cvss_report.pdf
          cp artifacts/$COVERITY_W/security_report.pdf \
             summary/sdl/CT39-StaticAnalysis/windows-security_report.pdf
          cp -r artifacts/$SSCB_L/. summary/sdl/CT151-CompilerFlags/
          cp -r artifacts/$SSCB_W/. summary/sdl/CT151-CompilerFlags/
          cp -r artifacts/$TRIVY/ct222-report.json \
           summary/sdl/CT222-DockerScan/
          cp -r artifacts/$TRIVY/trivy-report.csv summary/sdl/CT247-Trivy/

      - name: SWLC artifacts
        run: |
          mkdir -p summary/swlc/ip_leaks

          cp -r artifacts/$IPLEAKS/. summary/swlc/ip_leaks/

      - name: Quality artifacts
        if: >
          !cancelled()
        run: |
          mkdir -p summary/quality/acceptance/Ubuntu22.04/gen9.5
          mkdir -p summary/quality/acceptance/Ubuntu22.04/gen12.5
          mkdir -p summary/quality/acceptance/Win11/gen9.5
          mkdir -p summary/quality/acceptance/Win11/gen12.5
          mkdir -p summary/quality/acceptance/SLES15.4/gen12.5
          mkdir -p summary/quality/acceptance/RHEL8.6/gen12.5
          mkdir -p summary/quality/unit
          mkdir -p summary/quality/performance

          cp artifacts/$UTEST_L/*/Test.xml \
             summary/quality/unit/linux.xml
          cp artifacts/$UTEST_W/*/Test.xml \
             summary/quality/unit/windows.xml
          cp -r artifacts/$U2204_GEN95/. \
             summary/quality/acceptance/Ubuntu22.04/gen9.5/
          cp -r artifacts/$U2204/. \
            summary/quality/acceptance/Ubuntu22.04/gen12.5/
          cp -r artifacts/$WIN11_GEN95/. \
             summary/quality/acceptance/Win11/gen9.5/
          cp -r artifacts/$WIN11/. \
             summary/quality/acceptance/Win11/gen12.5/
          cp -r artifacts/$SLES154/. \
             summary/quality/acceptance/SLES15.4/gen12.5/
          cp -r artifacts/$RHEL86/. \
             summary/quality/acceptance/RHEL8.6/gen12.5/
          cp artifacts/linux-performance/summary.csv \
             summary/quality/performance/linux-performance-summary.csv
          cp artifacts/linux-performance/summary.md \
             summary/quality/performance/linux-performance-summary.md

      - name: Upload Summary
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output_prefix }}release-summary
          path: summary/*

      - name: Cleanup workspace
        run: sudo rm -rf ..?* .[!.]* *
